name: nymus tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, "12.16.1"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # yarn caches
      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Node full ICU support (needed for node.js < 12)
      - name: Get ICU cache dir
        id: icu-cache
        run: echo "::set-output name=dir::$(npm root -g)/full-icu"
      - name: Restore ICU data cache
        uses: actions/cache@v1
        id: full-icu-cache
        with:
          path: ${{ steps.icu-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-icu
      - name: Download ICU data
        id: full-icu
        if: steps.full-icu-cache.outputs.cache-hit != 'true'
        run: npm install -g full-icu

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn prettier

      - name: Build packages
        run: yarn build
        env:
          CI: true

      - name: Run tests
        run: yarn test
        env:
          CI: true
          TZ: Europe/Brussels
          NODE_ICU_DATA: ${{ steps.icu-cache.outputs.dir }}
